# Generated by Django 4.0.3 on 2024-03-05 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(default=datetime.date(2024, 3, 5))),
                ('thumbnail', models.FileField(upload_to='')),
                ('video_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
